services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    volumes:
      - /var/lib/mysql

  mysql_test:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3311:3306'
    volumes:
      - /var/lib/mysql2

volumes:
  cache:
    driver: local
